# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AV_rcpp <- function(voters, candidates, weights) {
    .Call(`_fastVoteR_AV_rcpp`, voters, candidates, weights)
}

seq_PAV_rcpp <- function(voters, candidates, weights, committee_size) {
    .Call(`_fastVoteR_seq_PAV_rcpp`, voters, candidates, weights, committee_size)
}

seq_Phragmen_rcpp <- function(voters, candidates, weights, committee_size) {
    .Call(`_fastVoteR_seq_Phragmen_rcpp`, voters, candidates, weights, committee_size)
}

SAV_rcpp <- function(voters, candidates, weights) {
    .Call(`_fastVoteR_SAV_rcpp`, voters, candidates, weights)
}

